-- Ramadan Planner 2026 (Bangladesh)
-- Auth: Google (Supabase Auth)
-- DB: profiles, ramadan_progress, prayer_times

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  division text check (division in ('Dhaka', 'Chattogram', 'Rajshahi', 'Khulna', 'Barishal', 'Sylhet', 'Rangpur', 'Mymensingh')),
  language text not null default 'bn' check (language in ('en', 'bn', 'ar')),
  theme text not null default 'light' check (theme in ('light', 'dark')),
  before_goals jsonb not null default '[]'::jsonb,
  during_goals jsonb not null default '[]'::jsonb,
  review jsonb not null default '{"gains":"","shortcomings":"","nextYearPlan":""}'::jsonb,
  special jsonb not null default '{"iitikafNights":[false,false,false,false,false,false,false,false,false,false],"qadrDuaDone":[false,false,false,false,false,false,false,false,false,false],"eidSunnah":[false,false,false,false,false,false]}'::jsonb,
  global_reflection text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ramadan_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ramadan_day smallint not null check (ramadan_day between 1 and 30),
  surah_completed boolean not null default false,
  hadith_completed boolean not null default false,
  record jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, ramadan_day)
);

create table if not exists public.prayer_times (
  id bigint generated by default as identity primary key,
  division text not null check (division in ('Dhaka', 'Chattogram', 'Rajshahi', 'Khulna', 'Barishal', 'Sylhet', 'Rangpur', 'Mymensingh')),
  ramadan_day smallint not null check (ramadan_day between 1 and 30),
  gregorian_date date not null,
  sehri_end time not null,
  iftar time not null,
  tahajjud_recommended time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (division, ramadan_day),
  unique (division, gregorian_date)
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists trg_ramadan_progress_updated_at on public.ramadan_progress;
create trigger trg_ramadan_progress_updated_at
before update on public.ramadan_progress
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists trg_prayer_times_updated_at on public.prayer_times;
create trigger trg_prayer_times_updated_at
before update on public.prayer_times
for each row
execute function public.set_updated_at_timestamp();

alter table public.profiles enable row level security;
alter table public.ramadan_progress enable row level security;
alter table public.prayer_times enable row level security;

alter table public.profiles replica identity full;
alter table public.ramadan_progress replica identity full;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists ramadan_progress_select_own on public.ramadan_progress;
create policy ramadan_progress_select_own
on public.ramadan_progress
for select
using (auth.uid() = user_id);

drop policy if exists ramadan_progress_insert_own on public.ramadan_progress;
create policy ramadan_progress_insert_own
on public.ramadan_progress
for insert
with check (auth.uid() = user_id);

drop policy if exists ramadan_progress_update_own on public.ramadan_progress;
create policy ramadan_progress_update_own
on public.ramadan_progress
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists ramadan_progress_delete_own on public.ramadan_progress;
create policy ramadan_progress_delete_own
on public.ramadan_progress
for delete
using (auth.uid() = user_id);

drop policy if exists prayer_times_select_authenticated on public.prayer_times;
create policy prayer_times_select_authenticated
on public.prayer_times
for select
to authenticated
using (true);

-- Ramadan 2026 official Dhaka baseline (Islamic Foundation) +
-- division-wise offsets for Bangladesh divisions.
delete from public.prayer_times
where gregorian_date between date '2026-02-19' and date '2026-03-20';

with dhaka_base as (
  select *
  from (
    values
      (1,  date '2026-02-19', time '05:12', time '17:58'),
      (2,  date '2026-02-20', time '05:11', time '17:59'),
      (3,  date '2026-02-21', time '05:10', time '17:59'),
      (4,  date '2026-02-22', time '05:09', time '18:00'),
      (5,  date '2026-02-23', time '05:08', time '18:00'),
      (6,  date '2026-02-24', time '05:07', time '18:01'),
      (7,  date '2026-02-25', time '05:06', time '18:01'),
      (8,  date '2026-02-26', time '05:05', time '18:02'),
      (9,  date '2026-02-27', time '05:04', time '18:02'),
      (10, date '2026-02-28', time '05:03', time '18:03'),
      (11, date '2026-03-01', time '05:02', time '18:03'),
      (12, date '2026-03-02', time '05:01', time '18:03'),
      (13, date '2026-03-03', time '05:00', time '18:04'),
      (14, date '2026-03-04', time '04:59', time '18:04'),
      (15, date '2026-03-05', time '04:58', time '18:05'),
      (16, date '2026-03-06', time '04:57', time '18:05'),
      (17, date '2026-03-07', time '04:56', time '18:06'),
      (18, date '2026-03-08', time '04:55', time '18:06'),
      (19, date '2026-03-09', time '04:53', time '18:06'),
      (20, date '2026-03-10', time '04:52', time '18:07'),
      (21, date '2026-03-11', time '04:51', time '18:07'),
      (22, date '2026-03-12', time '04:50', time '18:08'),
      (23, date '2026-03-13', time '04:49', time '18:08'),
      (24, date '2026-03-14', time '04:47', time '18:09'),
      (25, date '2026-03-15', time '04:46', time '18:09'),
      (26, date '2026-03-16', time '04:45', time '18:09'),
      (27, date '2026-03-17', time '04:44', time '18:10'),
      (28, date '2026-03-18', time '04:43', time '18:10'),
      (29, date '2026-03-19', time '04:41', time '18:11'),
      (30, date '2026-03-20', time '04:40', time '18:11')
  ) as v(ramadan_day, gregorian_date, sehri_end, iftar)
),
division_offsets as (
  select *
  from (
    values
      ('Dhaka', 0, 0),
      ('Chattogram', -5, -4),
      ('Rajshahi', 6, 6),
      ('Khulna', 4, 4),
      ('Barishal', -1, 1),
      ('Sylhet', -8, -8),
      ('Rangpur', 5, 4),
      ('Mymensingh', -1, -1)
  ) as o(division, sehri_offset_min, iftar_offset_min)
)
insert into public.prayer_times (
  division,
  ramadan_day,
  gregorian_date,
  sehri_end,
  iftar,
  tahajjud_recommended
)
select
  o.division,
  b.ramadan_day,
  b.gregorian_date,
  (b.sehri_end + make_interval(mins => o.sehri_offset_min))::time as sehri_end,
  (b.iftar + make_interval(mins => o.iftar_offset_min))::time as iftar,
  ((b.sehri_end + make_interval(mins => o.sehri_offset_min)) - interval '01:00')::time as tahajjud_recommended
from dhaka_base b
cross join division_offsets o
on conflict (division, gregorian_date)
do update set
  ramadan_day = excluded.ramadan_day,
  sehri_end = excluded.sehri_end,
  iftar = excluded.iftar,
  tahajjud_recommended = excluded.tahajjud_recommended,
  updated_at = now();
